# Generated by Django 4.1.7 on 2023-07-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sno',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
